---
- name: Deploy Product Deck
  hosts: webservers
  become: false

  tasks:

    - name: Stop backend container
      command: docker stop backend
      ignore_errors: yes

    - name: Remove backend container
      command: docker rm backend
      ignore_errors: yes

    - name: Stop frontend container
      command: docker stop frontend
      ignore_errors: yes

    - name: Remove frontend container
      command: docker rm frontend
      ignore_errors: yes

    - name: Start backend container
      command: docker run -d --name backend -p 8000:8000 product-deck-backend

    - name: Start frontend container
      command: docker run -d --name frontend -p 5173:5173 product-deck-frontend
